# Generated by Django 4.1.1 on 2022-10-10 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0016_alter_user_otp_request_time_addressdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_request_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 15, 19, 21, 941983)),
        ),
    ]
