# Generated by Django 4.1.1 on 2022-10-13 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0019_addressdetail_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_request_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 9, 1, 10, 489001)),
        ),
    ]
