# Generated by Django 4.1.1 on 2022-10-15 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0030_alter_user_otp_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_request_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 14, 27, 58, 494675)),
        ),
    ]
