# Generated by Django 4.1.1 on 2022-10-16 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0035_alter_user_otp_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_request_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 11, 58, 25, 377558)),
        ),
    ]
