# Generated by Django 4.1.1 on 2022-09-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Restraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('head_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('fssai_no', models.CharField(blank=True, max_length=100, null=True)),
                ('fssai_certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('rating', models.FloatField(default=4.2)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('closing_timing', models.TimeField(blank=True, null=True)),
                ('opening_timing', models.TimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restraunt_category', to='RestrauntApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='RestrauntMenuHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('restraunt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restraunt_menu', to='RestrauntApp.restraunt')),
            ],
        ),
        migrations.CreateModel(
            name='RestrauntMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_price', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_healthy', models.BooleanField(default=False)),
                ('is_veg', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('rating', models.FloatField(default=4.2)),
                ('total_sell', models.IntegerField(default=0)),
                ('menu_head', models.ManyToManyField(blank=True, related_name='restraunt_menu_head', to='RestrauntApp.restrauntmenuhead')),
            ],
        ),
        migrations.CreateModel(
            name='RestrauntBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('fssai_no', models.CharField(blank=True, max_length=100, null=True)),
                ('fssai_certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('rating', models.FloatField(default=4.2)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('restraunt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restraunt_branches', to='RestrauntApp.restraunt')),
            ],
        ),
    ]
