# Generated by Django 4.1.1 on 2022-09-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrauntmenu',
            name='menu_head',
            field=models.ManyToManyField(blank=True, to='RestrauntApp.restrauntmenuhead'),
        ),
    ]
