# Generated by Django 4.1.1 on 2022-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0002_alter_restrauntmenu_menu_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrauntmenu',
            name='menu_head',
            field=models.ManyToManyField(related_query_name='menu', to='RestrauntApp.restrauntmenuhead'),
        ),
    ]
