# Generated by Django 4.1.1 on 2022-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0003_alter_restrauntmenu_menu_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='maximum_delivery_radius',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='restrauntmenu',
            name='menu_head',
            field=models.ManyToManyField(related_name='menu', related_query_name='menu', to='RestrauntApp.restrauntmenuhead'),
        ),
    ]
