# Generated by Django 4.1.1 on 2022-09-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0004_restraunt_maximum_delivery_radius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDishHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('max_selection', models.IntegerField(default=1)),
                ('min_selection', models.IntegerField(default=1)),
                ('is_required', models.BooleanField(default=False)),
                ('is_additional_amount_calculated', models.BooleanField(default=False)),
                ('menu_dish', models.ManyToManyField(related_name='dish', related_query_name='dish', to='RestrauntApp.restrauntmenu')),
            ],
        ),
        migrations.CreateModel(
            name='CustomisationOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(default=0)),
                ('custom_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_dish_head', to='RestrauntApp.customdishhead')),
            ],
        ),
    ]
