# Generated by Django 4.1.1 on 2022-09-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0005_customdishhead_customisationoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrauntmenu',
            name='is_customisable',
            field=models.BooleanField(default=False),
        ),
    ]
