# Generated by Django 4.1.1 on 2022-10-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0008_cartitems_cartitemscustomisationhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='restraunt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restraunt_cart', to='RestrauntApp.restraunt'),
        ),
    ]
