# Generated by Django 4.1.1 on 2022-10-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0010_cartitems_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestrauntBranch',
        ),
    ]
