# Generated by Django 4.1.1 on 2022-10-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0011_delete_restrauntbranch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItemsCustomisationHead',
            new_name='CartCustomisedItem',
        ),
    ]
