# Generated by Django 4.1.1 on 2022-10-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0012_rename_cartitemscustomisationhead_cartcustomiseditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartcustomiseditem',
            name='price',
        ),
    ]
