# Generated by Django 4.1.1 on 2022-10-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0014_restrauntmenu_preparation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrauntSectionHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('restraunts', models.ManyToManyField(blank=True, null=True, related_name='section_restraunt', to='RestrauntApp.restraunt')),
            ],
        ),
    ]
