# Generated by Django 4.1.1 on 2022-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0016_restrauntsection_delete_restrauntsectionhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='')),
                ('restraunt', models.ManyToManyField(blank=True, related_name='special_restraunt', to='RestrauntApp.restraunt')),
            ],
        ),
    ]
