# Generated by Django 4.1.1 on 2022-10-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0017_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='restraunt',
            name='cuisine',
            field=models.ManyToManyField(blank=True, related_name='restraunt_cuisine', to='RestrauntApp.cuisine'),
        ),
    ]
