# Generated by Django 4.1.1 on 2022-10-14 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RestrauntApp', '0018_cuisine_restraunt_cuisine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('minimum_cart_amount', models.IntegerField(default=0)),
                ('discount_amount_limit', models.IntegerField(default=0)),
                ('limit_per_user', models.IntegerField(default=1)),
                ('offer_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_offer_by', to='RestrauntApp.restraunt')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='RestrauntApp.discountcoupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_used_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
