# Generated by Django 4.1.1 on 2022-10-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0019_discountcoupon_appliedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='cuisine_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
