# Generated by Django 4.1.1 on 2022-10-15 12:58

import RestrauntApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RestrauntApp', '0020_restraunt_cuisine_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=RestrauntApp.models.generateOrderId, max_length=30)),
                ('order_net_amount', models.FloatField(default=0)),
                ('order_tax_amount', models.FloatField(default=0)),
                ('order_tip_amount', models.FloatField(default=0)),
                ('order_delivery_amount', models.FloatField(default=0)),
                ('order_discount_amount', models.FloatField(default=0)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('is_cod', models.BooleanField(default=False)),
                ('item_count', models.IntegerField(default=0)),
                ('delivery_distance', models.FloatField(default=0)),
                ('net_delivery_time', models.FloatField(default=0)),
                ('delivery_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partner', to='RestrauntApp.restraunt')),
                ('restraunt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restraunt_order', to='RestrauntApp.restraunt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.FloatField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item', to='RestrauntApp.restrauntmenu')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='RestrauntApp.order')),
            ],
        ),
    ]
