# Generated by Django 4.1.1 on 2022-10-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0027_alter_user_otp_request_time'),
        ('RestrauntApp', '0021_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partner', to='CoreApp.deliverypartner'),
        ),
    ]
