# Generated by Django 4.1.1 on 2022-10-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0027_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dp_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='dp_longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='restraunt_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='restraunt_longitude',
            field=models.FloatField(default=0),
        ),
    ]
