# Generated by Django 4.1.1 on 2022-10-16 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0028_order_dp_latitude_order_dp_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Recieved', 'Order Recieved'), ('Order Confirmed', 'Order Confirmed'), ('Preparing Order', 'Preparing Order'), ('Delivery Partner at Restraunt', 'Delivery Partner at Restraunt'), ('Order Picked Up', 'Order Picked Up'), ('Delivered', 'Delivered')], default='Order Recieved', max_length=50),
        ),
    ]
