# Generated by Django 4.1.1 on 2022-10-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0029_order_order_date_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address_line_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
