# Generated by Django 4.1.1 on 2022-10-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0030_order_customer_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_address_line_1',
            new_name='customer_address',
        ),
    ]
