# Generated by Django 4.1.1 on 2022-10-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0031_rename_customer_address_line_1_order_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='cost_of_two',
            field=models.IntegerField(default=200),
        ),
    ]
