# Generated by Django 4.1.1 on 2022-10-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0033_restraunt_food_type_restraunt_is_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
