# Generated by Django 4.1.1 on 2023-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0037_restraunt_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
